
export const data = {
    bitcoin: 'Bitcoin',
    ethereum:'Ethereum',
    tether: 'Tether',
    binancecoin: 'Binance Coin',
    cardano: 'Cardano',
    ripple:'XRP',
    'usd-coin': 'USD Coin',
    dogecoin :'Dogecoin',
    polkadot: 'Polkadot',
    'binance-usd': 'Binance USD',
    uniswap: 'Uniswap',
    chainlink:'Chainlink',
    'bitcoin-cash':'Bitcoin Cash',
    solana:'Solana',
    litecoin:'Litecoin',
    'wrapped-bitcoin':'Wrapped Bitcoin',
    'matic-network':'Polygon',
    'ethereum-classic':'ethereum-classic',
    stellar:'Stellar',
    'theta-token':'Theta Network',
    'terra-luna':'Terra',
    vechain:'VeChain',
    dai:'Dai',
    'internet-computer':'Internet Compute',
    filecoin :'Filecoin',
    'compound-usd-coin':'cUSDC',
    okb:'OKB',
    tron:'TRON',
    monero:'Monero',
  }